---
service_name: "apache"
document_root: "/var/www/html"
log_directory: "/var/log/httpd"

required_packages:
  - httpd
  - mod_ssl
  - php

performance_settings:
  max_request_workers: 400
  threads_per_child: 25
  server_limit: 16

backup_schedule:
  frequency: "daily"
  retention_days: 7
  backup_path: "/backup/web"
