---
- name: Automated System Updates
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install security updates
      dnf:
        name: "*"
        state: latest
        security: yes

    - name: Install bugfix updates
      dnf:
        name: "*"
        state: latest
        bugfix: yes
