---
- name: Basic nginx handler demo
  hosts: localhost
  become: true

  tasks:
    - name: Update worker_processes
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^worker_processes'
        line: 'worker_processes 4;'
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

