---
- name: Web Server Setup with Tags
  hosts: webservers
  become: yes
  vars:
    web_package: httpd
    web_service: httpd
    document_root: /var/www/html

  tasks:
    - name: Install web server
      yum:
        name: "{{ web_package }}"
        state: present
      tags: install

    - name: Start service
      systemd:
        name: "{{ web_service }}"
        state: started
        enabled: yes
      tags: service

    - name: Create page
      copy:
        content: "<h1>{{ ansible_hostname }}</h1>"
        dest: "{{ document_root }}/index.html"
      tags: content
